WIP - there is a lot of MFA work right now and I want to enable iOS e2e testing
unfortunately most of it is set to skip, and I'm trying to figure out exactly what's broken

     NativeFirebaseError: [auth/multi-factor-auth-required] MFA_ENROLLMENT_NOT_FOUND